# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - Third Iteration 2024.1 

In [1]:
#pip install nbconvert pip install pyppeteer

In [4]:
#--allow-chromium-download

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [36]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [15]:
#Code comes here
arr1 = np.ones((1, 10, 1))
arr2 = np.arange(1, 20, 1)
arr3 = np.ones((5, 5), dtype="int")
print(arr1)
print(arr2)
print(arr3)
print(arr3.dtype)

[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
int64


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [17]:
# Code comes here
arr4 = np.random.randn(3, 3, 3)
print(arr4)
arr5 = arr4.reshape(27,)
print(arr5)

[[[-1.2743422   1.07109883  0.49302857]
  [-2.0226309   1.17583689  0.10989121]
  [ 0.52829507 -0.63357651  0.01638314]]

 [[-0.35040599  0.95910685 -0.11021063]
  [-1.67109185 -0.82948613  1.47726202]
  [-0.44778033  1.31426796 -0.93686301]]

 [[-0.05644439 -0.19082649 -2.02487283]
  [ 0.20159759  0.37847091 -0.20181784]
  [-0.34332633  0.86108764 -0.25960346]]]
[-1.2743422   1.07109883  0.49302857 -2.0226309   1.17583689  0.10989121
  0.52829507 -0.63357651  0.01638314 -0.35040599  0.95910685 -0.11021063
 -1.67109185 -0.82948613  1.47726202 -0.44778033  1.31426796 -0.93686301
 -0.05644439 -0.19082649 -2.02487283  0.20159759  0.37847091 -0.20181784
 -0.34332633  0.86108764 -0.25960346]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [19]:
# Code comes here
arr6 = np.random.randint(1, 10, 20)
print(arr6)

[6 7 1 7 3 8 5 6 5 1 4 4 2 4 9 8 6 6 6 4]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [32]:
import numpy as np
a = np.arange(1, 26, dtype=float).reshape(5, -1)
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]


In [ ]:
20

In [23]:
#Code goes here
print(a[3,4])

20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [25]:
# Code come here
print(a[1:, 3:])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [27]:
# Code comes here
array = a[1]
print(array)

[ 6  7  8  9 10]


## 2.5 

Calculate the sum of all the numbers in `a`.

In [35]:
# Code comes here
total = sum(a)

TypeError: 'int' object is not callable

## 2.6 

Calculate the sum of each row in `a`.

In [ ]:
# Code comes here

## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Code comes here


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [28]:
# Codes comes here
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [ ]:
# Code comes here

## 2.10 

How many rows and columns are there in the dataframe?

In [ ]:
#Code comes here

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [ ]:
# Code comes here

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [ ]:
# Code comes here

## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [ ]:
#code comes here

## 2.14

Which country consumes the least amount of beef per person per year?


In [ ]:
# code comes here

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [ ]:
# code comes here

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [ ]:
# code comes here

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.